### PR TITLE
fix(matmul): declare PermLayout::End() constexpr (GCC build fix for #97)

### PR DESCRIPTION
**Pull request by vanities**
Testing #97 per the call. The branch does not compile on Linux with GCC (tested 11.4.0):

```
src/matmul/matmul_v4_rc_stage3_recursive_parent_air.h:66:31: error: call to
non-'constexpr' function 'uint32_t matmul::v4::rc::air_recurse::PermLayout::End() const'
```

(also reached via `matmul_v4_rc_stage3_recursive_fixedpoint.h:279` and `:1591`.)

`PermLayout::End()` in `matmul_v4_rc_air_recurse.h` is called from constexpr functions that are constant-evaluated; a constant-evaluated call to a non-constexpr function is ill-formed. AppleClang accepts the current form, which is why Metal-side builds did not catch it.

One-line fix: declare `End()` constexpr (it is a trivial addition over constexpr members).

Verified on Linux x86_64 / GCC 11.4 / CUDA 13.3 / arch 120: full build completes (`btxd`, `test_btx`, `matmul-v4-rc-harness`) and `matmul_v4_rc_tests`, `matmul_verify_worker_tests`, `matmul_v4_lt_tests`, `matmul_v4_rc_coupled_tests`, `matmul_v4_rc_transcript_tests` all pass, including `rc_cuda_exact_replay_launch_abi_smoke` on CC 12.0 hardware. Full CUDA test report incoming on #97.

Suggest a Linux/GCC CI leg once workflows are re-enabled; this class of divergence is invisible to AppleClang-only builds.

### CODE REVIEW

**Comment by numair** [comment]
Accepted—thank you for finding and validating this Linux/GCC portability defect.

The one-line source change is now integrated into #97 as `a2cdfb2567696a946166144a389d056f284cc34d`. The resulting `src/matmul/matmul_v4_rc_air_recurse.h` content matches this PR exactly.

I applied the source change directly rather than cherry-picking this commit so #97 preserves the sanitized public noreply commit identity used by its publication/security sweep. Your report and Linux GCC/CUDA validation are credited in #97's conversation and validation section.

This is compile-time-only: `End()` computes the same value, and there is no change to consensus, ExactReplay output, mining work, chain data, or activation state. Since #97 now contains the fix, closing #98 as superseded/integrated.

We are not re-enabling GitHub Actions; Linux/GCC/CUDA remains a required local/manual validation lane.
